/* eslint-disable no-trailing-spaces */
/* eslint-disable indent */
export default [
    {
      diagnosis: 'Asthma',
      dx: 'Asthma',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    },
    {
      diagnosis: 'Diabetes',
      dx: 'Diabetes',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Back Pain',
      dx: 'Back Pain',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Hypertension',
      dx: 'HTN',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Rheumatoid Arthritis',
      dx: 'RA',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Kidney Stones',
      dx: 'Kidney Stones',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Gallstones',
      dx: 'Gallstones',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Reflux/ Gastritis',
      dx: 'GERD',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Ulcers',
      dx: 'PUD',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Cholesterol',
      dx: 'Dyslipidemia',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Valley Fever',
      dx: 'Coccidiomycosis',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Arthritis',
      dx: 'DJD',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Autoimmune',
      dx: 'Autoimmune',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Lupus',
      dx: 'SLE',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Thyroid Problems',
      dx: 'Thyroid',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Heart Attack',
      dx: 'MI',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Heart Failure',
      dx: 'CHF',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Heart Disease',
      dx: 'CAD',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Hepatitis',
      dx: 'Hepatitis',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'HIV/ AIDS',
      dx: 'HIV',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Stroke',
      dx: 'CVA',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Overweight',
      dx: 'Obesity',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Eczema',
      dx: 'Eczema',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Inflammatory Bowels',
      dx: 'IBD',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Irritable Bowels',
      dx: 'IBS',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Depression',
      dx: 'Depression',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Anxiety',
      dx: 'Anxiety',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Bipolar',
      dx: 'Bipolar',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Schizophrenia',
      dx: 'Schizophrenia',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Stress',
      dx: 'Stress',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    }, {
      diagnosis: 'Insomnia',
      dx: 'Insomnia',
      grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
    },
    {
     diagnosis: 'Cancer',
     dx: 'cancer',
     grandparents: false,
      mom: false,
      dad: false,
      siblings: false,
      children: false,
      auntuncle: false
   }
  ]
