/* eslint-disable */
export default {
  medications: [
    { 'generic': 'ibuprofen', 'brandNames': [ 'Motrin', 'Advil']},
    { 'generic': 'metformin', 'brandNames': [ 'Glucophage']},
    { 'generic': 'lisinopril', 'brandNames': [ 'Zestril' ]},
    { 'generic': 'aspirin', 'brandNames': [ 'Ecotrin' ]},
    { 'generic': 'pioglitazone', 'brandNames': [ 'Actos' ]},
    { 'generic': 'glipizide', 'brandNames': [ 'glucotrol' ]},
    { 'generic': 'losartan', 'brandNames': [ 'Cozaar' ]},
    { 'generic': 'valsartan', 'brandNames': [ 'Diovan' ]},
    { 'generic': 'simvastatin', 'brandNames': [ 'Zocor' ]},
    { 'generic': 'atorvastatin', 'brandNames': [ 'Lipitor' ]},
    { 'generic': 'rosuvastatin', 'brandNames': [ 'Crestor' ]},
    { 'generic': 'gemfibrazil', 'brandNames': [ 'Lopid' ]},
    { 'generic': 'celecoxib', 'brandNames': [ 'Celebrex' ]},
    { 'generic': 'furosemide', 'brandNames': [ 'Lasix' ]},
    { 'generic': 'carvedilol', 'brandNames': [ 'Coreg' ]},
    { 'generic': 'hydrochlorothiazide', 'brandNames': [ '' ]},
    { 'generic': 'hydrochlorothiazide/triamterene', 'brandNames': [ 'Dyazide' ]},
    { 'generic': 'acetaminophen', 'brandNames': [ 'Tylenol' ]},
    { 'generic': 'atenolol', 'brandNames': [ 'Tenormin' ]},
    { 'generic': 'clopidogrel', 'brandNames': [ 'Plavix' ]},
    { 'generic': 'warfarin', 'brandNames': [ 'Coumadin' ]},
    { 'generic': 'naproxen', 'brandNames': [ 'Naprosyn' ]},
    { 'generic': 'meloxicam', 'brandNames': [ 'Mobic' ]},
    { 'generic': 'alprazolam', 'brandNames': [ 'Xanax' ]},
    { 'generic': 'lorazepam', 'brandNames': [ 'Ativan' ]},
    { 'generic': 'canagliflozin', 'brandNames': [ 'Invokana' ]},
    { 'generic': 'empagliflozin', 'brandNames': [ 'Jardiance' ]},
    { 'generic': 'insulin', 'brandNames': [ '' ]},
    { 'generic': 'escitalopram', 'brandNames': [ 'Lexapro' ]},
    { 'generic': 'citalopram', 'brandNames': [ 'Celexa' ]},
    { 'generic': 'buproprion', 'brandNames': [ 'Wellbutrin' ]},
    { 'generic': 'fluoxetin', 'brandNames': [ 'Prozac' ]},
    { 'generic': 'paroxetine', 'brandNames': [ 'Paxil' ]},
    { 'generic': 'nifedipine', 'brandNames': [ 'Adalat', 'Nifedical', 'Procardia' ]},
    { 'generic': 'cyclobenzaprine', 'brandNames': [ 'flexeril' ]},
    { 'generic': 'carisoprodol', 'brandNames': [ 'Soma' ]},
    { 'generic': 'metaxalone', 'brandNames': [ 'Skelaxin' ]},
    { 'generic': 'loratidine', 'brandNames': [ 'Claritin' ]},
    { 'generic': 'fexofenadine', 'brandNames': [ 'Allegra' ]},
    { 'generic': 'Cetirizine', 'brandNames': [ 'Zyrtec' ]},
    { 'generic': 'diphenhydramine', 'brandNames': [ 'Benadryl' ]},
    { 'generic': 'fluticasone', 'brandNames': [ 'Flonase' ]},
    { 'generic': 'mometasone', 'brandNames': [ 'Nasonex' ]},
    { 'generic': 'prednisone', 'brandNames': [ '' ]},
    { 'generic': 'methotrexate', 'brandNames': [ '' ]},
    { 'generic': 'hydroxychloroquine', 'brandNames': [ 'Plaquenil' ]},
    { 'generic': 'albuterol', 'brandNames': [ 'Proventil', 'Proair' ]},
    { 'generic': 'levalbuterol', 'brandNames': [ 'Xopenex' ]},
    { 'generic': 'ipratropium/albuterol', 'brandNames': [ 'Combivent' ]},
    { 'generic': 'ipratropium', 'brandNames': [ 'Atrovent' ]},
    { 'generic': 'budesonide/formoterol', 'brandNames': [ 'Symbicort' ]},
    { 'generic': 'budesonide', 'brandNames': [ 'Pulmicort' ]},
    { 'generic': 'insulin detemir', 'brandNames': [ 'Levemir' ]},
    { 'generic': 'insuline glargine', 'brandNames': [ 'Lantus' ]},
    { 'generic': 'sitagliptin', 'brandNames': [ 'Januvia' ]},
    { 'generic': 'sitagliptin/metformin', 'brandNames': [ 'Janumet' ]},
  ]
}
