export default [
  {'name': 'back', dx: 'back surgery', checked: false},
  {'name': 'appendix', dx: 'appendectomy', checked: false},
  {'name': 'tonsils', dx: 'tonsillectomy', checked: false},
  {'name': 'gallbladder', dx: 'cholecystectomy', checked: false},
  {'name': 'kidney stones', dx: 'nephrolithiasis', checked: false},
  {'name': 'uterus', dx: 'hysterectomy', checked: false},
  {'name': 'ovaries', dx: 'oophorectomy', checked: false},
  {'name': 'knee', dx: 'knee replacement', checked: false},
  {'name': 'heart valves', dx: 'prosthetic heart valves', checked: false},
  {'name': 'heart bypass', dx: 'CABG', checked: false},
  {'name': 'heart stents', dx: 'cardiac stents', checked: false},
  {'name': 'hip', dx: 'hip replacement', checked: false},
  {'name': 'hernia', dx: 'hernia repair', checked: false},
  {'name': 'carpal tunnel', dx: 'CTS', checked: false},
  {'name': 'bariatrics', dx: 'bariatric surgery', checked: false},
  {'name': 'prostate', dx: 'prostatectomy', checked: false},
  {'name': 'breast biposy', dx: 'breast biopsy', checked: false},
  {'name': 'breast removal', dx: 'masectomy', checked: false},
  {'name': 'lung', dx: 'lung lobectomy', checked: false},
  {'name': 'colon', dx: 'colon resection', checked: false}
]
